feat: New option to make modal resizable
parse-community/parse-dashboard pull request #1885
Opened 2021-10-26 20:40 UTC by damianstasik

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR adds a "resize" handle to modals that have the `resizable` prop enabled.

Closes: #1879

### Approach

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2021-10-27 18:23 UTC, damianstasik commented
Here is how the final resize handle looks:
<img width="551" alt="Screen Shot 2021-10-27 at 20 22 07" src="https://user-images.githubusercontent.com/920747/139124348-7b8e0a4d-3025-4e97-8196-cc05540b9bce.png">

2021-10-27 18:55 UTC, damianstasik commented
@mtrezza regarding labels being resized as well: I tried to force a `max-width` on them, but the `Field` component would require a slightly bigger refactor that I did not want to include in this PR.

2021-10-27 20:32 UTC, mtrezza commented
That's fine then, thanks for looking into it.

2021-10-27 20:44 UTC, mtrezza requested changes
I tried it out and I wonder how we can combine the vertical and horizontal resizing by dragging the dialog corner. That the dialog can only be resized horizontally in the dialog corner and only vertically in the field corner is a rather unusual behavior.

There is also a bug that selects all text in the dialog when I resize horizontally:

https://user-images.githubusercontent.com/5673677/139144024-1725f5ea-4505-4820-ba92-97696648b230.mov

2021-10-30 20:27 UTC, visualfanatic commented
@mtrezza Maybe instead of the drag handle in the corner, we could allow resizing the modal with both the left and right edge of the container.

2021-10-30 21:08 UTC, mtrezza commented
Not sure how the experience of that would be. I can only think of a corner drag handle, like the field had. That is the UI behavior a user would expect. If there is another way that is intuitive, we can also explore that.

2021-10-30 21:12 UTC, visualfanatic commented
It could work as in a regular OS window manager, the whole side could be used to resize the modal:

https://user-images.githubusercontent.com/920747/139558468-ee3f470a-853f-4e58-9af2-32bb575d67d7.mov

2021-10-30 22:20 UTC, mtrezza commented
If it's separately resizable on the horizontal and vertical side it would certainly be an improvement over the status quo, but it would still be impractical when you cannot resize both simultaneously. I think that's an issue when you resize because there is a large JSON object that you want to display and you want to fit the dialog just right to display it.

2025-07-16 23:38 UTC, mtrezza commented
Superseded by https://github.com/parse-community/parse-dashboard/pull/2910

2025-07-16 23:38 UTC, closed without merging