refactor: upgrade styling deps
parse-community/parse-dashboard pull request #2300
Opened 2022-10-01 09:47 UTC by damianstasik

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
I updated `css-loader` and `sass-loader` to latest version, replaced `node-sass` with `sass` as the former is deprecated and fixed a few things that broke due the switch.

As a bonus we have one less critical vulnerability and a lot less dependencies.

Related issue: #1902

### Approach

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

2022-10-01 10:17 UTC, mtrezza commented
As usual, when this is ready for review please request a review.

2022-10-01 11:25 UTC, mtrezza requested changes

2022-10-01 11:25 UTC, mtrezza commented on package.json
> +    "sass": "^1.55.0",
```suggestion
    "sass": "1.55.0",
```

2022-10-01 11:25 UTC, mtrezza commented on package.json
>      "jest-environment-jsdom": "^29.1.2",
```suggestion
    "jest-environment-jsdom": "29.1.2",
```

2022-10-01 11:26 UTC, mtrezza approved these changes
Looks good! Waiting for CI...

2022-10-01 12:05 UTC, merged

2022-10-09 16:16 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.4)

2022-10-17 17:24 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

2022-11-01 20:56 UTC, parseplatformorg commented
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)