feat: allow export schemas
parse-community/parse-dashboard pull request #2362
Opened 2023-01-20 03:00 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Currently, it is not possible to export SCHEMA. The DefinedSchema guide recommends doing it via JS, which is not ideal.

https://docs.parseplatform.org/defined-schema/guide/#2-extract-schemas-using-js-console

Closes: #45

### Approach

Adds ability to extract SCHEMAS.

![Screenshot 2023-01-20 at 1 59 37 pm](https://user-images.githubusercontent.com/4974769/213608771-8c1edf75-9429-42a4-b6a6-6c7ca7b5e6d4.png)
![Screenshot 2023-01-20 at 2 00 11 pm](https://user-images.githubusercontent.com/4974769/213608776-7be4811b-d37b-400b-8be1-1baa66cafcb1.png)

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2023-01-20 15:22 UTC, mtrezza requested changes

2023-01-20 15:22 UTC, mtrezza commented on src/dashboard/Data/Browser/BrowserToolbar.react.js
> +            text={'Export SCHEMA'}
```suggestion
            text={'Export schema'}
```

2023-01-20 22:37 UTC, mtrezza approved these changes
Looks good!

2023-01-20 22:57 UTC, merged

2023-01-20 23:00 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.3)

2023-03-01 15:31 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

2023-05-01 23:04 UTC, parseplatformorg commented
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)