feat: allow exporting of classPreference
parse-community/parse-dashboard pull request #2455
Opened 2023-06-09 13:51 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Currently, filters have to be created every time and there's no way to define / export filters.

Closes: #2454

### Approach

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2023-06-09 15:40 UTC, mtrezza reviewed
Where would that feature be documented, so that users know it exists?

2023-06-10 04:37 UTC, dblythy commented
Added docs

2023-06-10 10:37 UTC, mtrezza commented on README.md
> +`classPreference` allows for filters to be saved across sessions. To save the current filters, navigate to App Settings and click "Export Class Preferences".
```suggestion
`classPreference` allows for filters to be saved across sessions. To save the current filters, navigate to *App Settings > Export Class Preferences*.

For example:
```

2023-06-10 10:38 UTC, mtrezza commented on README.md
> +`classPreference` allows for filters to be saved across sessions. To save the current filters, navigate to *App Settings > Export Class Preferences*.
```suggestion
The `classPreference` setting allows for filters to be saved across sessions. To save the current filters, navigate to *App Settings > Export Class Preferences*.
```

2023-06-10 10:41 UTC, mtrezza commented on README.md
> +```
````suggestion
```json
"apps": [{
  "classPreference": {
    "_Role": {
      "filters": [{
        "name": "Filter Name",
        "filter": "[{\"field\":\"objectId\",\"constraint\":\"exists\"}]"
      }]
    }
  }
}]
```
````

2023-06-10 10:44 UTC, mtrezza requested changes

2023-06-10 10:44 UTC, mtrezza commented on README.md
> +        "filter": "[{\"field\":\"objectId\",\"constraint\":\"exists\"}]"
About the filter value, why does its value need to be escaped? Why couldn't we just pass an object that would make it also more readable.

2023-06-10 13:08 UTC, mtrezza commented on README.md
>  run `parse-dashboard --createMFA` to generate a `mfa` secret that you then add to the existing user configuration, for example:
```suggestion
If you create a new user by running `parse-dashboard --createUser`, you will be  asked whether you want to enable MFA for the new user. To enable MFA for an existing user, run `parse-dashboard --createMFA` to generate a `mfa` secret that you then add to the existing user configuration, for example:
```

2023-06-10 13:08 UTC, mtrezza approved these changes, later dismissed
Looks good!

2023-06-10 13:20 UTC, mtrezza commented on README.md
> +The `classPreference` setting allows for data browser filters to be saved across sessions. To save the current filters, navigate to *App Settings > Export Class Preferences*.
```suggestion
The filters you save in the data browser of Parse Dashboard are only available for the current dashboard user in the current browser session. To make filters permanently available for all dashboard users of an app, you can define filters in the `classPreference` setting.
```

2023-06-10 13:22 UTC, mtrezza commented on README.md
> +
```suggestion

You can conveniently create a filter definition without having to write it by hand by first saving a filter in the data browser, then exporting the filter definition under *App Settings > Export Class Preferences*.

```

2023-06-10 13:23 UTC, mtrezza approved these changes

2023-06-10 13:29 UTC, merged

2023-06-10 13:32 UTC, parseplatformorg commented
🎉 This change has been released in version [5.2.0-alpha.13](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.13)

2023-06-10 14:03 UTC, parseplatformorg commented
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

2023-09-15 14:12 UTC, parseplatformorg commented
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)