feat: add ability to select script field
parse-community/parse-dashboard pull request #2488
Opened 2023-06-29 05:42 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Currently, `scripts` show on all fields, and every single value.

Closes: #2487
Closes: #2485

### Approach

Adds the following script syntax:

```js
"scripts": [
    {
    "title": "Delete account",
    "classes": [
      {
        "name": "_User",
        "fields": [{ "name": "createdAt", "validator": "value => value > new Date(\"2025\")" }]
      }
    ],
    "cloudCodeFunction": "deleteAccount"
  }
]
```

If using this syntax, the `script` will only show on a field defined in `fields`, and it will be `disabled` if the `validator` returns `false`. 

### TODOs before merging

- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2023-06-29 11:18 UTC, mtrezza commented
Wow, impressive PR!

2023-06-30 03:31 UTC, dblythy commented
Updated the syntax so the full Parse Object is passed through:

```js
"validator": (row, field) => row.get("field") > new Date(\"2025\")
```

2023-07-04 12:43 UTC, mtrezza reviewed
Could you resolve the conflicts? I've merged the lint and prettier [PR](https://github.com/parse-community/parse-dashboard/pull/2492).

2023-07-04 16:34 UTC, mtrezza reviewed
Could you also add a short example for this new feature to the README?

2023-07-05 07:59 UTC, mtrezza commented
Btw could you see whether the prettier hook works for you?

2023-07-18 00:31 UTC, dblythy commented
Didn't seem to run for me, perhaps my branch is outdated

2023-07-18 00:56 UTC, mtrezza commented
Maybe hooks don't get committed? If I add a hook at least I don't see anything to commit. Anyway, was just a side node.

2023-07-19 00:04 UTC, mtrezza requested changes

2023-07-19 00:04 UTC, mtrezza commented on Parse-Dashboard/parse-dashboard-config.json
> -      "serverURL": "http://localhost:1337/parse",
I assume you didn't intend to merge this?

2023-07-19 00:04 UTC, mtrezza commented on src/components/BrowserRow/BrowserRow.react.js
> +    const { className, columns, currentCol, isUnique, obj, onPointerClick, onPointerCmdClick, order, readOnlyFields, row, rowValue, rowWidth, selection, selectRow, setCopyableValue, setCurrent, setEd
Could you run prettier and eslint? Did looks like a long line that would be refactored

2023-07-20 19:24 UTC, mtrezza requested changes
Could you please ament the README to document this feature?

2023-07-21 22:35 UTC, mtrezza commented on README.md
> +        ],
Now that I see this syntax side by side, it seems to be a change in in field value type. The value for key `classes` is suddenly not `Array<String>` any more but can also be `Array<Object>`. If we released the scripts feature only in alpha and/or beta version we could make this breaking change and don't have to support `Array<String>` anymore to simplify code.

2023-08-27 22:44 UTC, mtrezza commented
@dblythy Could your take a look at the open questions? This seems almost ready to get merged.

2024-06-27 23:12 UTC, mtrezza commented on README.md
> +        ],
Leaving as is

2024-06-27 23:13 UTC, mtrezza approved these changes

2024-06-27 23:16 UTC, merged

2024-06-27 23:19 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.8)

2024-10-07 13:45 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.2)

2024-10-07 13:53 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)