feat: add security checks page
parse-community/parse-dashboard pull request #2491
Opened 2023-06-29 08:12 UTC by dblythy

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

There is currently no page to display security checks

Closes: #1665
### Approach

![Screenshot 2023-06-29 at 6 11 39 pm](https://github.com/parse-community/parse-dashboard/assets/4974769/28dab882-43a4-424c-84ed-1a33399ab5a0)

![Screenshot 2023-06-29 at 6 11 51 pm](https://github.com/parse-community/parse-dashboard/assets/4974769/9d0f7014-9033-44d8-9ac5-2560dfcce418)

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2023-06-29 12:11 UTC, mtrezza commented
Lovely!

2023-06-29 12:20 UTC, mtrezza requested changes

2023-06-29 12:20 UTC, mtrezza commented on src/dashboard/Settings/Security/Security.react.js
> +        <Fieldset legend="Result">
```suggestion
        <Fieldset legend="Overall Security Status">
```

2023-06-30 00:51 UTC, mtrezza commented
I'm not sure but for this feature to be implemented we may need to introduce a server option to hide the page per app or per user. It's exposing the security status of the server and its vulnerabilities. Any dashboard user can see this info easily, is that a good thing?

2023-06-30 03:15 UTC, dblythy commented
`security.enableCheck` is disabled by default on the server, so this is what shows:

![Screenshot 2023-06-30 at 1 13 45 pm](https://github.com/parse-community/parse-dashboard/assets/4974769/033baed1-9a1f-4984-ba96-bdf7ada9880c)

Perhaps we should pass this to `featuresRouter` and hide/show this page depending on the server settings?

2023-06-30 03:38 UTC, dblythy commented
Related: https://github.com/parse-community/parse-server/issues/8678

2023-07-03 00:18 UTC, mtrezza commented
That would mean that someone could not enable security checks if the didn't want to display possible attack vectors for all users in Parse Dashboard, right? If so, I'm not sure this would be an acceptable constraint. I think it should be possible to enable security checks on the server while hiding the results from the dashboard user.

If a dashboard user had access to the master key currently, and could access the security checks API anyway by inspecting the API requests, it may matter less, but I still think this kind of information should not be displayed so prominently to everyone.

2023-07-17 06:34 UTC, dblythy commented
![Screenshot 2023-07-17 at 4 34 35 pm](https://github.com/parse-community/parse-dashboard/assets/4974769/acec66df-fd6d-47b7-a98f-f6517edaa4c0)

2023-07-17 06:36 UTC, dblythy commented
I'm not sure if it's currently possible to specify features per user (other than readonly). I think the feature has to be either on for all users, or off for all. We can add an option `enableSecurityChecks: true` that can only show security checks if enabled in the dashboard config.

And yes, any dashboard user can inspect any network request to read the masterKey.

2023-07-17 16:27 UTC, mtrezza commented
Well, it's not that big of a deal then, but if you want to add an option to disable the security checks page in the dashboard config (for all apps or per app or per user, whatever is easiest), then I think it would be better. Otherwise I think we can merge it anyway.

Btw the new table layout looks nice! An additional luxury would be a refresh button, so developers can play around with the server settings and see the status change. Also just a suggestion, happy to merge without.

2023-07-18 00:54 UTC, dblythy commented
![Screenshot 2023-07-18 at 10 35 32 am](https://github.com/parse-community/parse-dashboard/assets/4974769/50f144de-d717-4d93-8dc5-e21d631c8757)

There is a reload button in the top right, I just missed it in the screenshot

2023-07-18 00:57 UTC, mtrezza commented
Nice!

2023-08-27 22:46 UTC, mtrezza approved these changes
Looks good!

2023-08-27 22:46 UTC, merged

2023-08-27 22:51 UTC, parseplatformorg commented
🎉 This change has been released in version [5.2.0-alpha.28](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.28)

2023-09-15 18:03 UTC, parseplatformorg commented
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

2023-09-20 13:18 UTC, parseplatformorg commented
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

2023-11-16 15:29 UTC, parseplatformorg commented
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)