fix: Info panel not showing when some apps miss infoPanel config
parse-community/parse-dashboard pull request #2627
Opened 2024-11-03 21:27 UTC by vardhan0604

### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Closes: #2623 

### Approach

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

2024-11-04 15:53 UTC, mtrezza requested changes

2024-11-04 15:53 UTC, mtrezza commented on src/dashboard/Data/Browser/Browser.react.js
> +  fetchAggregationPanelData(objectId, className, appID) {
```suggestion
  fetchAggregationPanelData(objectId, className, appId) {
```

Use camelCase for var names

2024-11-05 22:36 UTC, mtrezza approved these changes

2024-11-06 12:41 UTC, mtrezza requested changes
The "Show panel" button doesn't appear, when having a second app in dashboard config. Before this PR, a workaround was to add an empty panel `"infoPanel": [],`, but that doesn't work anymore either. Could you please verify the fix with the following configs:

1 app w/ panel:
```
{
  "apps": [
    {
      "serverURL": "https://app1.example.com",
      "appId": "appId1",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    }
  ]
}
```

2 apps, 1 w/ panel, 1 w/o panel:
```
{
  "apps": [
    {
      "serverURL": "https://app1.example.com",
      "appId": "appId1",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    },
    {
      "serverURL": "https://app2.example.com",
      "appId": "appId2",
      "masterKey": "masterKey",
      "appName": "app2"
    }
  ]
}
```

2 apps, 1 w/ panel, 1 w/ empty panel:
```
{
  "apps": [
    {
      "serverURL": "https://app1.example.com",
      "appId": "appId1",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    },
    {
      "serverURL": "https://app2.example.com",
      "appId": "appId2",
      "masterKey": "masterKey",
      "appName": "app2",
      "infoPanel": []
    }
  ]
}
```

2 apps, 2 w/ panel in different classes:
```
{
  "apps": [
    {
      "serverURL": "https://app1.example.com",
      "appId": "appId1",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    },
    {
      "serverURL": "https://app2.example.com",
      "appId": "appId2",
      "masterKey": "masterKey",
      "appName": "app2",
      "infoPanel": [
        {
          "title": "Installation Details",
          "classes": ["_Installation"],
          "cloudCodeFunction": "installation"
        }
      ]
    }
  ]
}
```

2024-11-06 19:30 UTC, vardhan0604 commented
@mtrezza, it’s working locally for me, but I'm not sure why it’s not working for you. I’ve pushed everything.
This is my config i used in this demo 
```
{
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "1234",
      "masterKey": "12345",
      "appName": "MyApp",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        },
        {
          "title": "Purchase Details",
          "classes": ["Purchase"],
          "cloudCodeFunction": "purchase"
        },
        {
          "title": "systumm h ladle",
          "classes": ["systum"],
          "cloudCodeFunction": "systum"
        }
      ]
    },
    {
      "serverURL": "https://app2.example.com",
      "appId": "appId2",
      "masterKey": "masterKey",
      "appName": "app2"
    }
  ]
}

```
https://github.com/user-attachments/assets/fab8ea6a-5585-48f6-a9e4-78cb78e35753

2024-11-07 01:01 UTC, mtrezza commented
Did you try our all the configs?

2024-11-07 18:01 UTC, vardhan0604 commented
> Did you try out all the configs from my previous comment? Some do not seem to work.

Yes @mtrezza , I tried all the configurations, and they seem to be working on my end. Could you let me know which specific ones aren’t working for you?

2024-12-16 01:05 UTC, mtrezza commented
Tested it out and from the pattern I guess the issue is with how you identify an app. The tests were actually done by adding the same app twice, hence both have the same app ID, same server URL, etc. I've added the exact configs and results below. I haven't looked at the code, but I guess you identify by app ID, hence they overwrite each other. At first I thought it was a testing mistake on my side. But then I tested the same with scripts and they work fine, even if there are 2 apps with the same app ID. I'd suggest you take a look at the script logic.

1 app w/ panel:
```
{
  "apps": [
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    }
  ]
}
```

alpha: OK
PR: OK

2 apps, 1 w/ panel, 1 w/o panel:
```
{
  "apps": [
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    },
    {
      "serverURL": "https://app2.example.com",
      "appId": "appId2",
      "masterKey": "masterKey",
      "appName": "app2"
    }
  ]
}
```

alpha: NOK:
- app1: no panel button
PR: OK

2 apps, 1 w/ panel, 1 w/ empty panel:
```
{
  "apps": [
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    },
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app2",
      "infoPanel": []
    }
  ]
}
```

alpha: OK
PR: NOK:
- app1: no panel button

2 apps, 2 w/ panel in same class:
```
{
  "apps": [
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user1"
        }
      ]
    },
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app2",
      "infoPanel": [
       {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user2"
        }
      ]
    }
  ]
}
```

alpha: NOK:
- app2: Cloud Function user1 is called instead of user2
PR: NOK:
- app1: Cloud Function user2 is called instead of user1

2 apps, 2 w/ panel in different classes:
```
{
  "apps": [
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app1",
      "infoPanel": [
        {
          "title": "User Details",
          "classes": ["_User"],
          "cloudCodeFunction": "user"
        }
      ]
    },
    {
      "serverURL": "https://example.com",
      "appId": "appId",
      "masterKey": "masterKey",
      "appName": "app2",
      "infoPanel": [
        {
          "title": "Installation Details",
          "classes": ["_Installation"],
          "cloudCodeFunction": "installation"
        }
      ]
    }
  ]
}
```

alpha: NOK:
- app2: Cloud Function user1 is called instead of user2
- app1: panel button is visible also in _Installation class
- app2: panel button is visible also in _User class
PR: NO:
- app1: panel button is visible in _Installation class instead of _User class

2024-12-20 10:21 UTC, vardhan0604 commented
Hey @mtrezza, can you please review the changes?

2024-12-20 13:44 UTC, mtrezza commented
@vardhan0604 is the fix just adding the app name as an additional identifier? Is that also how scripts identify the app? If so, what if it's the same app name and app ID, but a different URL - would it make sense to add the URL to it? 

Maybe a more robust solution would be to hash the app config object, which will create a unique ID assuming that an app config will never be completely the same as the other one.

2024-12-26 16:47 UTC, vardhan0604 commented
Hey @mtrezza ,  regarding how scripts identify the app, I tried understanding the codebase more. Apparently, in the `AppsManager`—where all the context related to each app is stored—it uses either the `appName` or the `slugName` (essentially the `appName` without special characters) to retrieve the app info.

I also noticed that if we have two apps with the same name, we cannot see the other app here.
![image](https://github.com/user-attachments/assets/acb9d9f7-73a4-4e5f-ac18-42192166493f)


Should we then assume that `appName` is a unique identifier for each app?

2025-01-11 20:51 UTC, mtrezza commented
I think that's currently a bug in dashboard, unless it's documented somewhere that app names must be unique?

2025-01-16 20:33 UTC, vardhan0604 commented
> I think that's currently a bug in dashboard, unless it's documented somewhere that app names must be unique?

Hey @mtrezza,

Thanks for your feedback! Based on what you've pointed out, it does seem like the current behavior might be a bug in the dashboard, especially if there's no documentation explicitly stating that app names must be unique. Relying on `appName` or `slugName` as unique identifiers could be problematic in scenarios where multiple apps have the same name.

To address this, I agree that `hashing` the app config object might be a more robust solution. However, as you mentioned, object key ordering could lead to inconsistencies in hash generation. A potential workaround could be normalizing the config object (e.g., sorting keys alphabetically) before hashing, ensuring consistent results.

Alternatively, we could explore combining multiple attributes—such as `appName`, `appID`, and `URL`—to create a composite unique identifier. This approach would account for scenarios where apps share the same name but differ in other aspects.

What are your thoughts on these?

2025-01-17 01:13 UTC, mtrezza commented
> Alternatively, we could explore combining multiple attributes—such as appName, appID, and URL—to create a composite unique identifier. 

That sounds good, but a maybe simpler approach: are the apps configs stored in an array in Parse Dashboard? An array has a defined order, so if apps are referenced by their array position which stays the same throughout the lifecycle of a dashboard instance, that could be a solution.

2025-01-23 23:58 UTC, mtrezza approved these changes
Looks good; @vardhan0604 I'l go ahead and merge this for now, so this issue doesn't block https://github.com/parse-community/parse-dashboard/pull/2622 any longer.

2025-01-23 23:59 UTC, merged

2025-01-24 00:02 UTC, parseplatformorg commented
🎉 This change has been released in version [6.0.0-alpha.21](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.21)

2025-01-24 05:24 UTC, vardhan0604 commented
Sure @mtrezza , sounds good. I'll go ahead and complete #2622 . I'll also start looking into the inconsistencies you mentioned as part of #2637 . Thanks!

2025-03-04 03:03 UTC, parseplatformorg commented
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.1.0)